const $=s=>document.querySelector(s);
const symbols=[['I',1,'un dedo'],['V',5,'una mano'],['X',10,'dos manos'],['L',50,'medio centenar'],['C',100,'centum'],['D',500,'quinientos'],['M',1000,'mille']];
const facts=['I se puede repetir hasta tres veces.','V nunca se repite.','X son dos V unidas.','L viene de una forma antigua de C.','C inicia la palabra latina centum.','D es la mitad de 1000.','M inicia la palabra latina mille.'];
const worlds=[
  {name:'I · I, V y X',icon:'🏛️',max:20,titles:['Uno, dos y tres','Conoce la V','IV: uno antes de cinco','De V a VIII','Primer repaso','Conoce la X','IX: uno antes de diez','De X a XIV','Hasta XX','Gran repaso I · V · X']},
  {name:'II · Camino a L',icon:'🛡️',max:99,titles:['Conoce la L','Decenas','XL significa 40','Mezcla I, V, X y L','Repaso hasta 99']},
  {name:'III · La centuria',icon:'🏺',max:399,titles:['Conoce la C','Las centenas','XC significa 90','CD significa 400','Repaso hasta 399']},
  {name:'IV · Grandes cifras',icon:'🦅',max:999,titles:['Conoce la D','De 400 a 600','CM significa 900','Mezcla completa','Repaso hasta 999']},
  {name:'V · Maestro de Roma',icon:'👑',max:3999,titles:['Conoce la M','Los millares','Fechas romanas','Todos los símbolos','Gran prueba final']}
];
const worldStart=index=>worlds.slice(0,index).reduce((sum,world)=>sum+world.titles.length,0);
const worldForLevel=level=>worlds.find((world,index)=>level>worldStart(index)&&level<=worldStart(index)+world.titles.length);
const avatars=['🦁','🦊','🐙','🦉','🐲','🐬'];

function toRoman(num){const map=[['M',1000],['CM',900],['D',500],['CD',400],['C',100],['XC',90],['L',50],['XL',40],['X',10],['IX',9],['V',5],['IV',4],['I',1]];let out='';for(const [r,v] of map)while(num>=v){out+=r;num-=v}return out}
function romanTiles(el,roman){el.innerHTML=[...roman].map(char=>`<i>${char}</i>`).join('');el.setAttribute('aria-label',[...roman].join(' '))}
function initialData(){return{active:null,profiles:[]}}
let data;try{data=JSON.parse(localStorage.getItem('romanum-v2'))||initialData()}catch{data=initialData()}
let sound=true,question=0,streak=0,current=1,answered=false,levelMode=null,levelScore=0,activeWorld=0;
const activeProfile=()=>data.profiles.find(p=>p.id===data.active);
const persist=()=>localStorage.setItem('romanum-v2',JSON.stringify(data));
function save(){persist();const p=activeProfile();$('#hero-stars').textContent=p?.stars||0;$('#hero-streak').textContent=p?.bestStreak||0;$('#profile-name').textContent=p?.name||'Elegir perfil';$('#profile-avatar').textContent=p?.avatar||'?';renderLevels();renderSymbols()}
function ensureProfile(){if(!activeProfile())$('#profile-dialog').showModal()}

const grid=$('#symbol-grid');function renderSymbols(){grid.innerHTML='';const available=(activeProfile()?.completed||0)>=10?symbols:symbols.slice(0,3);available.forEach(([roman,value,label],i)=>{const b=document.createElement('button');b.className='symbol-card';b.innerHTML=`<strong>${roman}</strong><span>${value}</span><small>${label}</small>`;b.addEventListener('click',()=>{b.classList.toggle('revealed');b.querySelector('small').textContent=b.classList.contains('revealed')?facts[i]:label});grid.appendChild(b)})}

function renderProfiles(){const list=$('#profile-list');list.innerHTML='';data.profiles.forEach(p=>{const b=document.createElement('button');b.type='button';b.className=`profile-option ${p.id===data.active?'active':''}`;b.innerHTML=`<span>${p.avatar}</span>${p.name}`;b.onclick=()=>{data.active=p.id;persist();$('#profile-dialog').close();save()};list.appendChild(b)})}
$('#profile-button').onclick=()=>{renderProfiles();$('#profile-dialog').showModal()};
$('#create-profile').onclick=()=>{const name=$('#new-profile-name').value.trim();if(!name)return;const id=Date.now().toString(36);data.profiles.push({id,name,avatar:avatars[data.profiles.length%avatars.length],stars:0,bestStreak:0,completed:0});data.active=id;$('#new-profile-name').value='';persist();renderProfiles();$('#profile-dialog').close();save()};

function renderWorldTabs(){const tabs=$('#world-tabs');tabs.innerHTML='';worlds.forEach((w,i)=>{const b=document.createElement('button');b.className='world-tab';b.role='tab';b.setAttribute('aria-selected',i===activeWorld);b.textContent=`${w.icon} ${w.name}`;b.onclick=()=>{activeWorld=i;renderWorldTabs();renderLevels()};tabs.appendChild(b)})}
function renderLevels(){if(!$('#level-map'))return;const p=activeProfile(),completed=p?.completed||0,w=worlds[activeWorld],start=worldStart(activeWorld);$('#level-map').innerHTML='';w.titles.forEach((title,i)=>{const n=start+i+1,done=n<=completed,open=n<=completed+1;const b=document.createElement('button');b.className=`level-card ${done?'done':''}`;b.disabled=!open;b.innerHTML=`<span class="level-number">${n}</span><span class="level-stars">${done?'★★★':open?'●':'🔒'}</span><h3>${title}</h3><p>${open?activeWorld===0?'Solo I, V y X':`Números hasta ${w.max}`:'Completa el nivel anterior'}</p>`;if(open)b.onclick=()=>startLevel(n);$('#level-map').appendChild(b)})}
function startLevel(n){ensureProfile();if(!activeProfile())return;levelMode=n;levelScore=0;question=0;newQuestion();$('#practicar').scrollIntoView({behavior:'smooth'})}
function maxForQuestion(){if(!levelMode)return 20;return worldForLevel(levelMode)?.max||20}
function randomValue(){if(!levelMode)return Math.floor(Math.random()*20)+1;const initialLimits=[3,5,5,8,8,10,10,14,20,20];if(levelMode<=10){const max=initialLimits[levelMode-1];return Math.floor(Math.random()*max)+1}const max=maxForQuestion();return Math.floor(Math.random()*Math.max(2,max-1))+2}
function beep(good=true){if(!sound)return;const a=new (window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=good?620:220;g.gain.setValueAtTime(.05,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.15);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.15)}
function newQuestion(){answered=false;current=randomValue();romanTiles($('#roman-prompt'),toRoman(current));const total=levelMode?5:10;$('#question-count').textContent=`Pregunta ${question+1} de ${total}${levelMode?` · Nivel ${levelMode}`:''}`;$('#progress-bar').style.width=`${((question+1)/total)*100}%`;$('#feedback').textContent='';$('#next-button').disabled=true;const choices=new Set([current]);while(choices.size<4)choices.add(Math.max(1,Math.min(maxForQuestion(),current+Math.floor(Math.random()*17)-8)));const box=$('#answer-grid');box.innerHTML='';[...choices].sort(()=>Math.random()-.5).forEach(n=>{const b=document.createElement('button');b.className='answer';b.textContent=n;b.onclick=()=>answer(n,b);box.appendChild(b)})}
function answer(n,b){if(answered)return;answered=true;document.querySelectorAll('.answer').forEach(x=>{x.disabled=true;if(+x.textContent===current)x.classList.add('correct')});const p=activeProfile();if(n===current){streak++;levelScore++;if(p){p.stars++;p.bestStreak=Math.max(p.bestStreak,streak)}$('#feedback').textContent='¡Perfecto! ⭐';beep()}else{streak=0;b.classList.add('wrong');$('#feedback').textContent=`Casi. ${toRoman(current)} vale ${current}.`;beep(false)}$('#streak-label').textContent=`🔥 ${streak}`;$('#next-button').disabled=false;save()}
$('#next-button').onclick=()=>{const total=levelMode?5:10;if(question+1>=total){if(levelMode){const p=activeProfile();if(levelScore>=4){p.completed=Math.max(p.completed,levelMode);$('#feedback').textContent=`¡Nivel ${levelMode} superado! Has desbloqueado el siguiente.`;save()}else $('#feedback').textContent=`Has acertado ${levelScore}/5. Necesitas 4 para superar el nivel.`;levelMode=null}question=0}else question++;newQuestion()};
$('#hint-button').onclick=()=>{$('#feedback').textContent=`Pista: está entre ${Math.max(1,current-5)} y ${current+5}.`};
$('#sound-toggle').onclick=e=>{sound=!sound;e.currentTarget.setAttribute('aria-pressed',sound);e.currentTarget.textContent=`${sound?'♪':'×'} Sonido`};

let timerId,challengeValue,challengeScore=0,time=60;function nextChallenge(){challengeValue=Math.floor(Math.random()*20)+1;$('#challenge-question').textContent=toRoman(challengeValue);$('#challenge-answer').value='';$('#challenge-answer').focus()}
$('#start-challenge').onclick=()=>{ensureProfile();if(!activeProfile())return;clearInterval(timerId);time=60;challengeScore=0;$('#timer').textContent=time;$('#challenge-score').textContent='0 aciertos';$('#challenge-answer').disabled=false;$('#challenge-submit').disabled=false;nextChallenge();timerId=setInterval(()=>{time--;$('#timer').textContent=time;if(time<=0){clearInterval(timerId);$('#challenge-answer').disabled=true;$('#challenge-submit').disabled=true;$('#challenge-question').textContent='¡Tiempo!';const p=activeProfile();p.stars+=challengeScore;save()}},1000)};
function submitChallenge(){if(+$(`#challenge-answer`).value===challengeValue){challengeScore++;$('#challenge-score').textContent=`${challengeScore} acierto${challengeScore===1?'':'s'}`;beep();nextChallenge()}else{beep(false);$('#challenge-answer').select()}}$('#challenge-submit').onclick=submitChallenge;$('#challenge-answer').addEventListener('keydown',e=>{if(e.key==='Enter')submitChallenge()});

let players=[],turn=0,round=0,groupValue=0;function addPlayer(name=''){if($('#player-fields').children.length>=6)return;const row=document.createElement('div');row.className='player-field';row.innerHTML=`<span>${avatars[$('#player-fields').children.length]}</span><input maxlength="14" placeholder="Nombre del jugador" value="${name}"><button class="remove-player" aria-label="Quitar jugador">×</button>`;row.querySelector('button').onclick=()=>{if($('#player-fields').children.length>2)row.remove()};$('#player-fields').appendChild(row)}
function groupQuestion(){const p=players[turn];$('#turn-name').textContent=p.name;groupValue=Math.floor(Math.random()*20)+1;romanTiles($('#group-roman'),toRoman(groupValue));$('#group-answer').value='';$('#group-feedback').textContent='';$('#group-answer').focus();renderScore()}
function renderScore(){$('#score-list').innerHTML=players.length?players.map((p,i)=>`<div class="score-row"><span>${avatars[i]} ${p.name}${i===turn?' ←':''}</span><strong>${p.score} ★</strong></div>`).join(''):'<p>Añade jugadores para empezar.</p>'}
$('#add-player').onclick=()=>addPlayer();$('#start-group').onclick=()=>{players=[...document.querySelectorAll('.player-field input')].map((x,i)=>({name:x.value.trim()||`Jugador ${i+1}`,score:0}));if(players.length<2)return;turn=0;round=0;$('#group-setup').hidden=true;$('#group-game').hidden=false;$('#reset-group').hidden=false;groupQuestion()};
function groupSubmit(){const good=+$('#group-answer').value===groupValue;if(good){players[turn].score++;$('#group-feedback').textContent='¡Correcto! Ganas una estrella.';beep()}else{$('#group-feedback').textContent=`Era ${groupValue}.`;beep(false)}renderScore();setTimeout(()=>{turn=(turn+1)%players.length;if(turn===0)round++;if(round>=5){$('#group-game').hidden=true;$('#score-list').insertAdjacentHTML('afterbegin','<p><b>¡Partida terminada!</b></p>')}else groupQuestion()},900)}$('#group-submit').onclick=groupSubmit;$('#group-answer').addEventListener('keydown',e=>{if(e.key==='Enter')groupSubmit()});$('#reset-group').onclick=()=>{$('#group-game').hidden=true;$('#group-setup').hidden=false;$('#reset-group').hidden=true;players=[];renderScore()};
$('#reset-progress').onclick=()=>{if(confirm('¿Borrar el progreso del perfil actual?')){const p=activeProfile();if(p){p.stars=0;p.bestStreak=0;p.completed=0;save()}}};
addPlayer();addPlayer();renderWorldTabs();renderProfiles();save();newQuestion();setTimeout(ensureProfile,250);
