const symbols=[['I',1,'un dedo'],['V',5,'una mano'],['X',10,'dos manos'],['L',50,'medio centenar'],['C',100,'centum'],['D',500,'quinientos'],['M',1000,'mille']];
const facts=['I se puede repetir hasta tres veces.','V nunca se repite.','X son dos V unidas.','L viene de una forma antigua de C.','C inicia la palabra latina centum.','D es la mitad de 1000.','M inicia la palabra latina mille.'];
const grid=document.querySelector('#symbol-grid');
symbols.forEach(([roman,value,label],i)=>{const b=document.createElement('button');b.className='symbol-card';b.innerHTML=`<strong>${roman}</strong><span>${value}</span><small>${label}</small>`;b.addEventListener('click',()=>{b.classList.toggle('revealed');b.querySelector('small').textContent=b.classList.contains('revealed')?facts[i]:label});grid.appendChild(b)});

function toRoman(num){const map=[['M',1000],['CM',900],['D',500],['CD',400],['C',100],['XC',90],['L',50],['XL',40],['X',10],['IX',9],['V',5],['IV',4],['I',1]];let out='';for(const [r,v] of map)while(num>=v){out+=r;num-=v}return out}
let state=JSON.parse(localStorage.getItem('romanum-progress')||'{"stars":0,"bestStreak":0}');
let sound=true,question=0,streak=0,current,answered=false;
const $=s=>document.querySelector(s);const save=()=>{localStorage.setItem('romanum-progress',JSON.stringify(state));$('#hero-stars').textContent=state.stars;$('#hero-streak').textContent=state.bestStreak};
function beep(good=true){if(!sound)return;const a=new (window.AudioContext||window.webkitAudioContext)(),o=a.createOscillator(),g=a.createGain();o.frequency.value=good?620:220;g.gain.setValueAtTime(.06,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.16);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.16)}
function newQuestion(){answered=false;current=Math.floor(Math.random()*89)+2;$('#roman-prompt').textContent=toRoman(current);$('#question-count').textContent=`Pregunta ${question+1} de 10`;$('#progress-bar').style.width=`${(question+1)*10}%`;$('#feedback').textContent='';$('#next-button').disabled=true;const choices=new Set([current]);while(choices.size<4)choices.add(Math.max(1,current+Math.floor(Math.random()*17)-8));const box=$('#answer-grid');box.innerHTML='';[...choices].sort(()=>Math.random()-.5).forEach(n=>{const b=document.createElement('button');b.className='answer';b.textContent=n;b.onclick=()=>answer(n,b);box.appendChild(b)})}
function answer(n,b){if(answered)return;answered=true;document.querySelectorAll('.answer').forEach(x=>{x.disabled=true;if(+x.textContent===current)x.classList.add('correct')});if(n===current){streak++;state.stars++;state.bestStreak=Math.max(state.bestStreak,streak);$('#feedback').textContent='¡Perfecto! ⭐';beep()}else{streak=0;b.classList.add('wrong');$('#feedback').textContent=`Casi. ${toRoman(current)} vale ${current}.`;beep(false)}$('#streak-label').textContent=`🔥 ${streak}`;$('#next-button').disabled=false;save()}
$('#next-button').onclick=()=>{question=(question+1)%10;newQuestion()};
$('#hint-button').onclick=()=>{$('#feedback').textContent=`Pista: está entre ${Math.max(1,current-5)} y ${current+5}.`};
$('#sound-toggle').onclick=e=>{sound=!sound;e.currentTarget.setAttribute('aria-pressed',sound);e.currentTarget.setAttribute('aria-label',sound?'Desactivar sonidos':'Activar sonidos');e.currentTarget.innerHTML=`${sound?'♪':'×'} <span>Sonido</span>`};
let timerId,challengeValue,challengeScore=0,time=60;
function nextChallenge(){challengeValue=Math.floor(Math.random()*199)+1;$('#challenge-question').textContent=toRoman(challengeValue);$('#challenge-answer').value='';$('#challenge-answer').focus()}
$('#start-challenge').onclick=()=>{clearInterval(timerId);time=60;challengeScore=0;$('#challenge-score').textContent='0 aciertos';$('#challenge-answer').disabled=false;$('#challenge-submit').disabled=false;nextChallenge();timerId=setInterval(()=>{time--;$('#timer').textContent=time;if(time<=0){clearInterval(timerId);$('#challenge-answer').disabled=true;$('#challenge-submit').disabled=true;$('#challenge-question').textContent='¡Tiempo!';state.stars+=challengeScore;save()}},1000)};
function submitChallenge(){if(+$(`#challenge-answer`).value===challengeValue){challengeScore++;$('#challenge-score').textContent=`${challengeScore} acierto${challengeScore===1?'':'s'}`;beep();nextChallenge()}else{beep(false);$('#challenge-answer').select()}}
$('#challenge-submit').onclick=submitChallenge;$('#challenge-answer').addEventListener('keydown',e=>{if(e.key==='Enter')submitChallenge()});
$('#reset-progress').onclick=()=>{if(confirm('¿Quieres borrar tus estrellas y tu mejor racha?')){state={stars:0,bestStreak:0};save()}};
save();newQuestion();
