import{load,save}from'../core/storage.js?v=20260712b';
import{tone,speak}from'../core/sounds.js?v=20260712b';
import{readingWords,readingLevels}from'../data/reading-data.js?v=20260712b';

const $=s=>document.querySelector(s),ROUND_LENGTH=8;
let progress=load('reading',{hits:0,attempts:0,best:0,completedRounds:0});
let level=null,order=[],index=0,stars=0,locked=false,flashTimer=null;

function shuffle(values){const list=[...values];for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}return list}
function persist(){save('reading',progress)}
function renderMenu(){const box=$('#reading-levels');box.innerHTML='';readingLevels.forEach(item=>{const button=document.createElement('button');button.className='reading-level-card';button.innerHTML=`<span>${item.id}</span><div><b>${item.label}</b><small>${item.desc}</small></div>`;button.onclick=()=>startLevel(item);box.appendChild(button)})}
function startLevel(selected){clearTimeout(flashTimer);level=selected;order=shuffle(readingWords).slice(0,ROUND_LENGTH);index=0;stars=0;locked=false;$('#reading-stars').textContent=stars;$('#reading-celebrate').hidden=true;$('#reading-menu').hidden=true;$('#reading-play').hidden=false;renderQuestion()}
function showMenu(){clearTimeout(flashTimer);$('#reading-play').hidden=true;$('#reading-celebrate').hidden=true;$('#reading-menu').hidden=false}
function renderDots(){$('#reading-dots').innerHTML=order.map((_,position)=>`<i class="${position<index?'done':position===index?'active':''}"></i>`).join('')}
function pickDistractors(target,count,strategy){let pool=readingWords.filter(item=>item.word!==target.word);if(strategy==='far'){let filtered=pool.filter(item=>item.word[0]!==target.word[0]&&Math.abs(item.word.length-target.word.length)>=1);if(filtered.length<count)filtered=pool.filter(item=>item.word[0]!==target.word[0]);pool=filtered}else if(strategy==='mid')pool=pool.filter(item=>item.word[0]!==target.word[0]);if(pool.length<count)pool=readingWords.filter(item=>item.word!==target.word);return shuffle(pool).slice(0,count)}
function renderOptions(target){const choices=shuffle([target,...pickDistractors(target,level.options-1,level.strategy)]),box=$('#reading-choices');box.className=`reading-options cols-${level.options}`;box.innerHTML='';choices.forEach(item=>{const button=document.createElement('button');button.className='reading-option';button.textContent=item.word.toUpperCase();button.onclick=()=>answer(button,item.word,target.word);box.appendChild(button)})}
function hideActivity(){$('#reading-image').hidden=true;$('#reading-listen').hidden=true;$('#reading-flash').hidden=true;$('#reading-choices').hidden=false}
function renderQuestion(){locked=false;$('#reading-feedback').textContent='';$('#reading-feedback').className='reading-feedback';const target=order[index];hideActivity();if(level.mode==='listen'){$('#reading-listen').hidden=false;$('#reading-prompt').textContent='Escucha y toca la palabra';$('#reading-listen').onclick=()=>speak(target.word);speak(target.word);renderOptions(target)}else if(level.mode==='flash'){locked=true;$('#reading-flash').hidden=false;$('#reading-flash').textContent=target.word.toUpperCase();$('#reading-prompt').textContent='Memoriza la palabra';$('#reading-choices').hidden=true;flashTimer=setTimeout(()=>{$('#reading-flash').hidden=true;$('#reading-prompt').textContent='¿Cuál era la palabra?';$('#reading-choices').hidden=false;renderOptions(target);locked=false},2000)}else{const picture=$('#reading-image');picture.hidden=false;picture.innerHTML=target.art||target.icon;picture.setAttribute('aria-label',target.alt);$('#reading-prompt').textContent='Toca la palabra de…';renderOptions(target)}renderDots()}
function answer(button,chosen,correct){if(locked)return;progress.attempts++;if(chosen===correct){locked=true;button.classList.add('correct');$('#reading-feedback').textContent='¡Muy bien! 🙌';$('#reading-feedback').classList.add('ok');stars++;progress.hits++;progress.best=Math.max(progress.best,stars);$('#reading-stars').textContent=stars;tone();persist();setTimeout(()=>{index++;if(index>=order.length){progress.completedRounds++;persist();$('#reading-play').hidden=true;$('#reading-final-score').textContent=`${stars} estrellas de ${ROUND_LENGTH}`;$('#reading-celebrate').hidden=false}else renderQuestion()},700)}else{button.classList.add('wrong');$('#reading-feedback').textContent='Inténtalo otra vez';$('#reading-feedback').classList.add('no');tone('error');persist();setTimeout(()=>{button.classList.remove('wrong');locked=false},500)}}
export function initReading(){renderMenu();$('#reading-back').onclick=showMenu;$('#reading-restart').onclick=()=>startLevel(level);$('#reading-again').onclick=()=>startLevel(level);$('#reading-to-menu').onclick=showMenu}
