import{load,save}from'../core/storage.js';import{tone}from'../core/sounds.js';import{romanSymbols,toRoman,fromRoman}from'../data/roman-data.js';
const $=s=>document.querySelector(s);let state=load('roman',{active:'Explorador',profiles:{Explorador:{stars:0,best:0}}});let current=1,direction='toArabic',streak=0,answered=false;let timer,challengeValue=1,challengeScore=0;let players=[],turn=0,round=0,groupValue=1;
function profile(){return state.profiles[state.active]}
function persist(){save('roman',state);renderStats()}
function renderProfiles(){const select=$('#roman-profile');select.innerHTML=Object.keys(state.profiles).map(name=>`<option${name===state.active?' selected':''}>${name}</option>`).join('')}
function renderStats(){$('#roman-stats').textContent=`${profile().stars} estrellas · Mejor racha: ${profile().best}`;renderProfiles()}
function tiles(el,roman){el.innerHTML=[...roman].map(char=>`<i>${char}</i>`).join('');el.setAttribute('aria-label',[...roman].join(' '))}
function choicesAround(value){const values=new Set([value]);while(values.size<4){const candidate=Math.max(1,Math.min(3999,value+Math.floor(Math.random()*19)-9));values.add(candidate)}return[...values].sort(()=>Math.random()-.5)}
function newQuestion(){answered=false;direction=Math.random()>.5?'toArabic':'toRoman';current=Math.floor(Math.random()*199)+1;$('#roman-direction').textContent=direction==='toArabic'?'ROMANO → NÚMERO':'NÚMERO → ROMANO';if(direction==='toArabic')tiles($('#roman-prompt'),toRoman(current));else{$('#roman-prompt').innerHTML=`<strong>${current}</strong>`;$('#roman-prompt').setAttribute('aria-label',String(current))}$('#roman-question-label').textContent=direction==='toArabic'?'¿Qué número es?':'¿Cómo se escribe en romano?';$('#roman-feedback').textContent='';$('#roman-next').disabled=true;const values=choicesAround(current),box=$('#roman-choices');box.innerHTML='';values.forEach(value=>{const button=document.createElement('button');button.className='choice';button.textContent=direction==='toArabic'?value:toRoman(value);button.onclick=()=>answer(value,button);box.appendChild(button)})}
function answer(value,button){if(answered)return;answered=true;document.querySelectorAll('#roman-choices .choice').forEach(item=>{item.disabled=true;const correct=direction==='toArabic'?+item.textContent===current:item.textContent===toRoman(current);if(correct)item.classList.add('correct')});if(value===current){streak++;profile().stars++;profile().best=Math.max(profile().best,streak);$('#roman-feedback').textContent='¡Muy bien! Ganas una estrella ⭐';tone()}else{streak=0;button.classList.add('wrong');$('#roman-feedback').textContent=`La respuesta es ${direction==='toArabic'?current:toRoman(current)}.`;tone('error')}$('#roman-streak').textContent=`🔥 ${streak}`;$('#roman-next').disabled=false;persist()}
function renderSymbols(){const box=$('#roman-symbols');box.innerHTML='';romanSymbols.forEach(([roman,value,label])=>{const button=document.createElement('button');button.className='symbol';button.innerHTML=`<strong>${roman}</strong><span>${value}</span><small>${label}</small>`;button.onclick=()=>{button.querySelector('small').textContent=`${roman} vale ${value}`;tone('next')};box.appendChild(button)})}
function nextChallenge(){challengeValue=Math.floor(Math.random()*199)+1;const useRoman=Math.random()>.5;$('#challenge-prompt').textContent=useRoman?toRoman(challengeValue):challengeValue;$('#challenge-input').dataset.kind=useRoman?'number':'roman';$('#challenge-input').value='';$('#challenge-input').placeholder=useRoman?'Número':'Romano';$('#challenge-input').focus()}
function checkChallenge(){const input=$('#challenge-input'),answer=input.dataset.kind==='number'?+input.value:fromRoman(input.value);if(answer===challengeValue){challengeScore++;$('#challenge-score').textContent=`${challengeScore} aciertos`;tone();nextChallenge()}else{tone('error');input.select()}}
function addPlayer(){if($('#group-names').children.length>=6)return;const row=document.createElement('div');row.className='player-row';row.innerHTML=`<input maxlength="14" aria-label="Nombre del jugador" placeholder="Jugador ${$('#group-names').children.length+1}"><button class="secondary" aria-label="Quitar jugador">×</button>`;row.querySelector('button').onclick=()=>{if($('#group-names').children.length>2)row.remove()};$('#group-names').appendChild(row)}
function renderScore(){$('#group-score').innerHTML=players.length?players.map((p,i)=>`<div class="score-line"><span>${p.name}${i===turn?' ←':''}</span><b>${p.score} ★</b></div>`).join(''):'Añade jugadores para empezar.'}
function groupQuestion(){groupValue=Math.floor(Math.random()*99)+1;$('#group-turn').textContent=players[turn].name;tiles($('#group-prompt'),toRoman(groupValue));$('#group-input').value='';$('#group-feedback').textContent='';renderScore();$('#group-input').focus()}
function groupCheck(){const good=+$('#group-input').value===groupValue;if(good){players[turn].score++;$('#group-feedback').textContent='¡Correcto! ⭐';tone()}else{$('#group-feedback').textContent=`Era ${groupValue}.`;tone('error')}renderScore();setTimeout(()=>{turn=(turn+1)%players.length;if(turn===0)round++;if(round===5){$('#group-play').hidden=true;$('#group-score').insertAdjacentHTML('afterbegin','<p><b>¡Partida terminada!</b></p>')}else groupQuestion()},800)}
export function initRoman(){renderSymbols();renderStats();newQuestion();$('#roman-profile').onchange=e=>{state.active=e.target.value;persist();newQuestion()};$('#add-profile').onclick=()=>{const name=window.prompt('Nombre del nuevo perfil:')?.trim();if(name&&!state.profiles[name]){state.profiles[name]={stars:0,best:0};state.active=name;persist()}};$('#roman-next').onclick=newQuestion;$('#roman-hint').onclick=()=>{$('#roman-feedback').textContent=direction==='toArabic'?`Está entre ${Math.max(1,current-5)} y ${current+5}.`:`Empieza por ${toRoman(current)[0]}.`};$('#challenge-start').onclick=()=>{clearInterval(timer);let time=60;challengeScore=0;$('#challenge-time').textContent=time;$('#challenge-score').textContent='0 aciertos';$('#challenge-input').disabled=false;$('#challenge-check').disabled=false;nextChallenge();timer=setInterval(()=>{time--;$('#challenge-time').textContent=time;if(time<=0){clearInterval(timer);$('#challenge-input').disabled=true;$('#challenge-check').disabled=true;$('#challenge-prompt').textContent='¡Tiempo!';profile().stars+=challengeScore;persist()}},1000)};$('#challenge-check').onclick=checkChallenge;$('#challenge-input').onkeydown=e=>{if(e.key==='Enter')checkChallenge()};addPlayer();addPlayer();$('#group-add').onclick=addPlayer;$('#group-start').onclick=()=>{players=[...document.querySelectorAll('#group-names input')].map((input,i)=>({name:input.value.trim()||`Jugador ${i+1}`,score:0}));turn=0;round=0;$('#group-setup').hidden=true;$('#group-play').hidden=false;$('#group-reset').hidden=false;groupQuestion()};$('#group-check').onclick=groupCheck;$('#group-input').onkeydown=e=>{if(e.key==='Enter')groupCheck()};$('#group-reset').onclick=()=>{$('#group-play').hidden=true;$('#group-setup').hidden=false;$('#group-reset').hidden=true;players=[];renderScore()}}
