import{load,save}from'../core/storage.js';import{tone}from'../core/sounds.js';import{romanSymbols,toRoman,fromRoman}from'../data/roman-data.js';
const $=s=>document.querySelector(s);const worlds=[
 {name:'I · I, V y X',icon:'🏛️',max:20,titles:['Uno, dos y tres','Conoce la V','IV: uno antes de cinco','De V a VIII','Primer repaso','Conoce la X','IX: uno antes de diez','De X a XIV','Hasta XX','Gran repaso']},
 {name:'II · Camino a L',icon:'🛡️',max:99,titles:['Conoce la L','Las decenas','XL significa 40','Combina I, V, X y L','Repaso hasta 99']},
 {name:'III · La centuria',icon:'🏺',max:399,titles:['Conoce la C','Las centenas','XC significa 90','Números hasta 300','Repaso hasta 399']},
 {name:'IV · Grandes cifras',icon:'🦅',max:999,titles:['Conoce la D','De 400 a 600','CM significa 900','Mezcla completa','Repaso hasta 999']},
 {name:'V · Maestro de Roma',icon:'👑',max:3999,titles:['Conoce la M','Los millares','Fechas romanas','Todos los símbolos','Gran prueba final']}
];const worldStart=index=>worlds.slice(0,index).reduce((sum,world)=>sum+world.titles.length,0);const worldForLevel=level=>worlds.find((world,index)=>level>worldStart(index)&&level<=worldStart(index)+world.titles.length);let activeWorld=0;let state=load('roman',{active:'Explorador',profiles:{Explorador:{stars:0,best:0,completed:0}}});Object.values(state.profiles).forEach(p=>{p.completed??=0});let current=1,direction='toArabic',streak=0,answered=false,level=null,levelQuestion=0,levelScore=0;let timer,challengeValue=1,challengeScore=0;let players=[],turn=0,round=0,groupValue=1;
function profile(){return state.profiles[state.active]}
function persist(){save('roman',state);renderStats()}
function renderProfiles(){const select=$('#roman-profile');select.innerHTML=Object.keys(state.profiles).map(name=>`<option${name===state.active?' selected':''}>${name}</option>`).join('')}
function renderStats(){$('#roman-stats').textContent=`${profile().stars} estrellas · Mejor racha: ${profile().best}`;$('#roman-hero-stars').textContent=profile().stars;$('#roman-hero-best').textContent=profile().best;renderProfiles();renderLevels()}
function tiles(el,roman){el.innerHTML=[...roman].map(char=>`<i>${char}</i>`).join('');el.setAttribute('aria-label',[...roman].join(' '))}
function questionMax(){if(!level)return 199;if(level<=10)return[3,5,5,8,8,10,10,14,20,20][level-1];return worldForLevel(level)?.max||199}
function choicesAround(value){const ceiling=Math.max(4,questionMax()),values=new Set([value]);while(values.size<4){const candidate=Math.max(1,Math.min(ceiling,value+Math.floor(Math.random()*19)-9));values.add(candidate)}return[...values].sort(()=>Math.random()-.5)}
function newQuestion(){answered=false;direction=Math.random()>.5?'toArabic':'toRoman';current=Math.floor(Math.random()*questionMax())+1;$('#roman-question-count').textContent=level?`Pregunta ${levelQuestion+1} de 5 · Nivel ${level}`:'Práctica libre';$('#roman-progress').style.width=level?`${(levelQuestion+1)*20}%`:'0';$('#roman-direction').textContent=direction==='toArabic'?'ROMANO → NÚMERO':'NÚMERO → ROMANO';if(direction==='toArabic')tiles($('#roman-prompt'),toRoman(current));else{$('#roman-prompt').innerHTML=`<strong>${current}</strong>`;$('#roman-prompt').setAttribute('aria-label',String(current))}$('#roman-question-label').textContent=direction==='toArabic'?'¿Qué número es?':'¿Cómo se escribe en romano?';$('#roman-feedback').textContent='';$('#roman-next').disabled=true;const values=choicesAround(current),box=$('#roman-choices');box.innerHTML='';values.forEach(value=>{const button=document.createElement('button');button.className='choice';button.textContent=direction==='toArabic'?value:toRoman(value);button.onclick=()=>answer(value,button);box.appendChild(button)})}
function answer(value,button){if(answered)return;answered=true;document.querySelectorAll('#roman-choices .choice').forEach(item=>{item.disabled=true;const correct=direction==='toArabic'?+item.textContent===current:item.textContent===toRoman(current);if(correct)item.classList.add('correct')});if(value===current){streak++;levelScore++;profile().stars++;profile().best=Math.max(profile().best,streak);$('#roman-feedback').textContent='¡Muy bien! Ganas una estrella ⭐';tone()}else{streak=0;button.classList.add('wrong');$('#roman-feedback').textContent=`La respuesta es ${direction==='toArabic'?current:toRoman(current)}.`;tone('error')}$('#roman-streak').textContent=`🔥 ${streak}`;$('#roman-next').disabled=false;persist()}
function renderWorldTabs(){const box=$('#roman-world-tabs');box.innerHTML='';worlds.forEach((world,index)=>{const button=document.createElement('button');button.className='world-tab';button.role='tab';button.setAttribute('aria-selected',index===activeWorld);button.textContent=`${world.icon} ${world.name}`;button.onclick=()=>{activeWorld=index;renderWorldTabs();renderLevels()};box.appendChild(button)})}
function renderLevels(){const box=$('#roman-level-map');if(!box)return;box.innerHTML='';const world=worlds[activeWorld],start=worldStart(activeWorld),completed=profile().completed||0;world.titles.forEach((title,index)=>{const number=start+index+1,done=number<=completed,open=number<=completed+1;const button=document.createElement('button');button.className=`level-card${done?' done':''}`;button.disabled=!open;button.innerHTML=`<span class="level-number">${number}</span><span class="level-stars">${done?'★★★':open?'●':'🔒'}</span><h3>${title}</h3><p>${open?`Números hasta ${world.max}`:'Completa el anterior'}</p>`;if(open)button.onclick=()=>{level=number;levelQuestion=0;levelScore=0;newQuestion();$('#roman-practice').scrollIntoView({behavior:'smooth'})};box.appendChild(button)})}
function nextPractice(){if(level&&levelQuestion===4){if(levelScore>=4){profile().completed=Math.max(profile().completed||0,level);$('#roman-feedback').textContent=`¡Nivel ${level} superado!`;persist()}else $('#roman-feedback').textContent=`Has acertado ${levelScore} de 5. Necesitas 4.`;level=null;levelQuestion=0;levelScore=0;$('#roman-question-count').textContent='Práctica libre';$('#roman-progress').style.width='0';$('#roman-next').disabled=true;return}if(level)levelQuestion++;newQuestion()}
function renderSymbols(){const box=$('#roman-symbols');box.innerHTML='';romanSymbols.forEach(([roman,value,label])=>{const button=document.createElement('button');button.className='symbol';button.innerHTML=`<strong>${roman}</strong><span>${value}</span><small>${label}</small>`;button.onclick=()=>{button.querySelector('small').textContent=`${roman} vale ${value}`;tone('next')};box.appendChild(button)})}
function nextChallenge(){challengeValue=Math.floor(Math.random()*199)+1;const useRoman=Math.random()>.5;$('#challenge-prompt').textContent=useRoman?toRoman(challengeValue):challengeValue;$('#challenge-input').dataset.kind=useRoman?'number':'roman';$('#challenge-input').value='';$('#challenge-input').placeholder=useRoman?'Número':'Romano';$('#challenge-input').focus()}
function checkChallenge(){const input=$('#challenge-input'),answer=input.dataset.kind==='number'?+input.value:fromRoman(input.value);if(answer===challengeValue){challengeScore++;$('#challenge-score').textContent=`${challengeScore} aciertos`;tone();nextChallenge()}else{tone('error');input.select()}}
function addPlayer(){if($('#group-names').children.length>=6)return;const row=document.createElement('div');row.className='player-row';row.innerHTML=`<input maxlength="14" aria-label="Nombre del jugador" placeholder="Jugador ${$('#group-names').children.length+1}"><button class="secondary" aria-label="Quitar jugador">×</button>`;row.querySelector('button').onclick=()=>{if($('#group-names').children.length>2)row.remove()};$('#group-names').appendChild(row)}
function renderScore(){$('#group-score').innerHTML=players.length?players.map((p,i)=>`<div class="score-line"><span>${p.name}${i===turn?' ←':''}</span><b>${p.score} ★</b></div>`).join(''):'Añade jugadores para empezar.'}
function groupQuestion(){groupValue=Math.floor(Math.random()*99)+1;$('#group-turn').textContent=players[turn].name;tiles($('#group-prompt'),toRoman(groupValue));$('#group-input').value='';$('#group-feedback').textContent='';renderScore();$('#group-input').focus()}
function groupCheck(){const good=+$('#group-input').value===groupValue;if(good){players[turn].score++;$('#group-feedback').textContent='¡Correcto! ⭐';tone()}else{$('#group-feedback').textContent=`Era ${groupValue}.`;tone('error')}renderScore();setTimeout(()=>{turn=(turn+1)%players.length;if(turn===0)round++;if(round===5){$('#group-play').hidden=true;$('#group-score').insertAdjacentHTML('afterbegin','<p><b>¡Partida terminada!</b></p>')}else groupQuestion()},800)}
export function initRoman(){renderSymbols();renderWorldTabs();renderStats();newQuestion();$('#roman-profile').onchange=e=>{state.active=e.target.value;persist();newQuestion()};$('#add-profile').onclick=()=>{const name=window.prompt('Nombre del nuevo perfil:')?.trim();if(name&&!state.profiles[name]){state.profiles[name]={stars:0,best:0,completed:0};state.active=name;persist()}};$('#roman-next').onclick=nextPractice;$('#challenge-start').onclick=()=>{clearInterval(timer);let time=60;challengeScore=0;$('#challenge-time').textContent=time;$('#challenge-score').textContent='0 aciertos';$('#challenge-input').disabled=false;$('#challenge-check').disabled=false;nextChallenge();timer=setInterval(()=>{time--;$('#challenge-time').textContent=time;if(time<=0){clearInterval(timer);$('#challenge-input').disabled=true;$('#challenge-check').disabled=true;$('#challenge-prompt').textContent='¡Tiempo!';profile().stars+=challengeScore;persist()}},1000)};$('#challenge-check').onclick=checkChallenge;$('#challenge-input').onkeydown=e=>{if(e.key==='Enter')checkChallenge()};addPlayer();addPlayer();$('#group-add').onclick=addPlayer;$('#group-start').onclick=()=>{players=[...document.querySelectorAll('#group-names input')].map((input,i)=>({name:input.value.trim()||`Jugador ${i+1}`,score:0}));turn=0;round=0;$('#group-setup').hidden=true;$('#group-play').hidden=false;$('#group-reset').hidden=false;groupQuestion()};$('#group-check').onclick=groupCheck;$('#group-input').onkeydown=e=>{if(e.key==='Enter')groupCheck()};$('#group-reset').onclick=()=>{$('#group-play').hidden=true;$('#group-setup').hidden=false;$('#group-reset').hidden=true;players=[];renderScore()}}
